var tagsData = [
    "#Adult Content", "#Profile Features Limited", "#Singleplayer", "#Crime", "#Third Person",
    "#Resource Management", "#Open World", "#Tactical", "#Survival", "#Sandbox",
    "#Assassin", "#Shooter", "#Story Rich", "#Atmospheric", "#Stealth",
    "#Indie", "#Action", "#Strategy", "#Simulation", "#Difficult",
    "#Adventure", "#Casual", "#Free", "#RPG", "#First Person",
    "#Fantasy", "#Sport", "#Action RPG", "#Dark Fantasy", "#Lore Rich",
    "#Horror", "#Racing", "#Souls Like", "#Mythology",
];

var productData = [
    {
        id: 1237,
        name: "God Of War",
        tags: "#Singleplayer #Third Person #Story Rich #Atmospheric #Action #Difficult #Adventure #RPG #Lore Rich #Mythology",
        previewInfo: {
            title: "God Of War",
            previewImage: "img/product_img/godofwar/big_preview/1.jpg",
            price: 649,
        },
        fullInfo: {
            category: "Games",
            platform: ["Play Station 4","Play Station 5","PC"],
            images: [
                "img/product_img/godofwar/big_preview/1.jpg",
                "img/product_img/godofwar/big_preview/2.jpg",
                "img/product_img/godofwar/big_preview/3.jpg",
                "img/product_img/godofwar/big_preview/4.jpg",
                "img/product_img/godofwar/big_preview/5.jpg",
                "img/product_img/godofwar/big_preview/6.jpg",
                "img/product_img/godofwar/big_preview/7.jpg",
                "img/product_img/godofwar/big_preview/8.jpg",
                "img/product_img/godofwar/big_preview/9.jpg",
                "img/product_img/godofwar/big_preview/10.jpg",
            ],
            description: "Many years have passed since the titular God of War, Kratos took his vengeance against the Olympian gods. Having survived his final encounter with his father Zeus, Kratos has since travelled to Midgard in Ancient Norway and now lives with his young son Atreus in the world of the Norse gods, a savage land inhabited by many ferocious monsters and warriors. In order to teach his son, whose mother (and Kratos's second wife) has recently died, how to survive in such a world, Kratos must master the rage that has driven him for many years and embrace his newfound role as a father and a mentor",
        },
    },
    {
        id: 1230,
        name: "The Last Of Us: Remastered",
        tags: "#Singleplayer #Third Person #Open World #Survival #Sandbox #Shooter #Story Rich #Atmospheric #Stealth #Action #Adventure",
        previewInfo: {
            title: "The Last Of Us: Remastered",
            previewImage: "img/product_img/tlou_remastered/7.jpg",
            price: 340,
        },
        fullInfo: {
            category: "Games",
            platform: ["Play Station 4","Play Station 5"],
            images: [
                "img/product_img/tlou_remastered/1.jpg",
                "img/product_img/tlou_remastered/2.jpg",
                "img/product_img/tlou_remastered/3.jpg",
                "img/product_img/tlou_remastered/4.jpg",
                "img/product_img/tlou_remastered/5.jpg",
                "img/product_img/tlou_remastered/6.jpg",
                "img/product_img/tlou_remastered/7.jpg",
            ],
            description: "Experience the emotional storytelling and unforgettable characters of Joel and Ellie in The Last of Us, and explore the events that changed the lives of Ellie and her best friend Riley forever in the critically acclaimed prequel chapter, Left Behind. A total overhaul of the original experience, faithfully reproduced but incorporating modernized gameplay mechanics, improved controls and expanded accessibility options. Feel immersed in improved environmental storytelling, effects, facial animations, and enhanced exploration and combat",
        },
    },
    {
        id: 1720,
        name: "Spider Man",
        tags: "#Singleplayer #Third Person #Open World #Sandbox #Assassin #Shooter #Story Rich #Stealth #Action #Adventure",
        previewInfo: {
            title: "Spider Man 2018",
            previewImage: "img/product_img/spiderman_2018/1.jpg",
            price: 1199,
        },
        fullInfo: {
            category: "Games",
            platform: ["Play Station 4","PC","Play Station 5"],
            images: [
                "img/product_img/spiderman_2018/1.jpg",
                "img/product_img/spiderman_2018/2.jpg",
                "img/product_img/spiderman_2018/3.jpg",
                "img/product_img/spiderman_2018/4.jpg",
                "img/product_img/spiderman_2018/5.jpg",
                "img/product_img/spiderman_2018/6.jpg",
                "img/product_img/spiderman_2018/7.jpg",
                "img/product_img/spiderman_2018/8.jpg",
            ],
            description: "Sony Interactive Entertainment, Insomniac Games, and Marvel have teamed up to create an authentic Spider-Man adventure. This isn’t the Spider-Man you’ve met or ever seen before. This is an experienced Peter Parker who’s more masterful at fighting big crime in Marvel's New York. At the same time, he’s struggling to balance his chaotic personal life and career while the fate of millions of New Yorkers rest upon his shoulders. After eight years behind the mask, Peter Parker is a crime-fighting expert. Feel the full power of a more experienced Spider-Man with improvisational combat, dynamic acrobatics, fluid urban traversal, and environmental interactions. A rookie no longer, this is the most masterful Spider-Man you’ve ever played",
        },
    },
    {
        id: 3892,
        name: "Bloodborne",
        tags: "#Third Person #Story Rich #Atmospheric #Action #Difficult #Adventure #Dark Fantasy #Lore Rich #Souls Like #RPG",
        previewInfo: {
            title: "Bloodborne",
            previewImage: "img/product_img/bloodborne/1.png",
            price: 649,
        },
        fullInfo: {
            category: "Games",
            platform: ["Play Station 4","Play Station 5"],
            images: [
                "img/product_img/bloodborne/1.png",
                "img/product_img/bloodborne/2.png",
                "img/product_img/bloodborne/3.png",
                "img/product_img/bloodborne/4.png",
                "img/product_img/bloodborne/5.png",
                "img/product_img/bloodborne/6.png",
                "img/product_img/bloodborne/7.jpg",
                "img/product_img/bloodborne/8.jpg",
            ],
            description: "Bloodborne follows the player's character, a Hunter, through the decrepit Gothic, Victorian-era–inspired city of Yharnam, whose inhabitants are afflicted with a blood-borne disease. Attempting to find the source of the plague, the player's character unravels the city's mysteries while fighting beasts and cosmic beings. Hunt your nightmares as you search for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like wildfire. Danger, death and madness lurk around every corner of this dark and horrific world, and you must discover its darkest secrets in order to survive.",
        },
    },
    {
        id: 1289,
        name: "Sekiro: Shadows Die Twice",
        tags: "#Third Person #Story Rich #Atmospheric #Action #Difficult #Adventure #Fantasy #Lore Rich #Souls Like #RPG",
        previewInfo: {
            title: "Sekiro: Shadows Die Twice",
            previewImage: "img/product_img/sekiro/big_preview/1.jpg",
            price: 1600,
        },
        fullInfo: {
            category: "Games",
            platform: ["Play Station 4", "Play Station 5", "PC", "Xbox"],
            images: [
                "img/product_img/sekiro/big_preview/1.jpg",
                "img/product_img/sekiro/big_preview/2.jpg",
                "img/product_img/sekiro/big_preview/3.jpg",
                "img/product_img/sekiro/big_preview/4.jpg",
                "img/product_img/sekiro/big_preview/5.jpg",
            ],
            description: "In Sekiro: Shadows Die Twice you are the “one-armed wolf”, a disgraced and disfigured warrior rescued from the brink of death. Bound to protect a young lord who is the descendant of an ancient bloodline, you become the target of many vicious enemies, including the dangerous Ashina clan. When the young lord is captured, nothing will stop you on a perilous quest to regain your honor, not even death itself. Explore late 1500s Sengoku Japan, a brutal period of constant life and death conflict, as you come face to face with larger than life foes in a dark and twisted world. Unleash an arsenal of deadly prosthetic tools and powerful ninja abilities while you blend stealth, vertical traversal, and visceral head to head combat in a bloody confrontation.",
        },
    },
];